# -*- coding: utf-8 -*-
"""Salinan dari Selamat Datang di Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vfh-JYwZ-c0igQTRrShgxSi0nSi8o_Nl

<div class="markdown-google-sans">
  <h1>Selamat Datang di Colab!</h1>
</div>

<!-- TODO(b/319266067) remove temporary advert after a few weeks. -->
<div class="markdown-google-sans">
  <h2>&#40;Baru&#41; Coba Gemini API</h2>
  <ul>
  <li><a href="https://makersuite.google.com/app/apikey">Generate a Gemini API key</a></li>
  <li><a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google%27s_Speech_to_Text_API.ipynb?utm_medium=link&utm_campaign=gemini">Talk to Gemini with the Speech-to-Text API</a></li>
  <li><a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Learning_with_Gemini_and_ChatGPT.ipynb?utm_medium=link&utm_campaign=gemini">Compare Gemini with ChatGPT</a></li>  
  <li><a href="https://colab.google/notebooks/?utm_medium=link&utm_campaign=gemini">More notebooks</a></li>
  </ul>
</div>

<div class="markdown-google-sans">
  <h2>Apa itu Colab?</h2>
</div>

Colab, atau "Colaboratory", memungkinkan Anda menulis dan mengeksekusi Python di browser, dengan
- Tidak memerlukan konfigurasi
- Akses tanpa biaya ke GPU
- Berbagi dengan mudah

Apakah Anda seorang <strong>pelajar</strong>, <strong>data scientist</strong>, atau <strong>peneliti AI</strong>, Colab dapat memudahkan pekerjaan Anda. Tonton <a href="https://www.youtube.com/watch?v=inN8seMm7UI">Pengantar Colab</a> untuk mempelajari lebih lanjut, atau langsung mulai di bawah ini.

#Business Understanding

##Business Objective
Tujuan Pada bisnis Adidas Fashion dataset ini dimulai dari pemahaman akan kekuatan oalahraga dalam mengubah kehidupan. Pendekatan ini yang menjadikan landasan bagi pengelolaan perusahaan, untuk meningkatkan penjualan produk, kesadaran merek, dan kepuasan pelanggan, serta mengoptimalkan persediaan, ekspansi pasar, dan margin keuntungan. Selain itu, focus pada bisnis ini juga diberikan pada pengembangan produk, pengurangan biaya operasional, peningkatan retensi pelanggan, dan konversi penjualan. Dengan merumuskan objektif ini, Adidas dapat mengembangkan strategi yang tepat dan mengukur kinerja bisnis mereka berdasarkan data yang ada dalam dataset tersebut.

##Asseess Situastion
Dalam situasi bisnis yang telah di analisis ini adalah untuk membangun fondasi yang kuat untuk masa depan dengan focus pada pengurangan investaris dan diskon pada 2023. Tujuannya untuk kembali menjadi bisnis yang menguntungkan pada tahun 2024. Adidas akan kembali menekankan pada produk, konsumen,mitra ritel,dan atlet, sambil memperkuat sumber daya manusia dan budaya perusahaan. Adidas juga harus bekerja sama dengan mitra lokal untuk meningkatkan distribusi produk dan memastikan ketersediaan produk yang memadai di toko-toko. Selain itu, Adidas perlu memperkuat kesadaran merek melalui kampanye pemasaran yang relevan dengan budaya dan tren lokal. Meskipun menghadapi tantangan,  serta mengimplementasikan langkah-langkah untuk mencapai kembali pertumbuhan yang menguntungkan. dan tetap optimis dalam melihat masa depan perusahaan.

#Data Mining Goals
Tujuan dari data mining pada dataset produk ritel fashion Adidas adalah untuk mengidentifikasi pola-pola dan wawasan yang berguna bagi perusahaan dalam mengambil keputusan strategis. terkait manajemen persediaan, optimasi saluran penjualan, pengembangan produk, pemasaran yang lebih efektif, serta perencanaan keuangan jangka panjang. Melalui analisis data mining, Adidas berharap untuk dapat memahami perilaku pembelian pelanggan, tren produk, preferensi konsumen, serta faktor-faktor lain yang memengaruhi kinerja bisnis dari Adidas. Dengan pemahaman yang lebih mendalam tentang data, Adidas dapat mengoptimalkan strategi pemasaran, manajemen persediaan, pengembangan produk, dan pengambilan keputusan lainnya untuk mencapai tujuan bisnis mereka secara efektif.

#Project Plan
Rencana proyek untuk analisis dataset ini dengan membuat pengumpulan data pada komprehensif dari berbagai sumber termasuk penjualan, investaris, dan data pelanggan. Selanjutkan akan dilakukan pembersihan data untuk menghilangkan duplikasi, nilai-nilai yang hilang, dan kesalahan lainnya agar data lebih akurat. Kemudian dilakukan analisis pada data menggunakan data mining untuk mengidentifikasi dari pola-pola, tren, dan wawasan yang relavan. Kemudian hasil dari analisis ini akan digunakan untuk merumuskan srategi bisnis, seperti peningkatan pemasaran dan manajemen persediaan yang lebih efisien. Dan dilakukan evaluasi dan penyususnana laporan untuk mengkomunikasikan hasil analisis kepada pemangku kepentingan dan membuat rekomendasi untuk tindakan selanjutnya.

<div class="markdown-google-sans">

## <strong>Memulai</strong>
</div>

Dokumen yang sedang Anda baca bukan halaman statis. Ini media interaktif bernama <strong>notebook Colab</strong> yang memungkinkan Anda menulis dan mengeksekusi kode.

Misalnya, berikut ini <strong>kode sel</strong> dengan skrip Python pendek yang mengomputasi sebuah nilai, menyimpannya dalam suatu variabel, dan mencetak hasilnya:
"""

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""Untuk mengeksekusi kode dalam sel di atas, pilih kode tersebut dengan mengkliknya, kemudian tekan tombol putar di sebelah kiri kode atau gunakan pintasan keyboard "Command/Ctrl+Enter". Untuk mengedit kode, cukup klik sel dan mulai pengeditan.

Variabel yang Anda tentukan dalam sebuah sel nantinya dapat digunakan di sel lain:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Notebook Colab memungkinkan Anda menggabungkan <strong>kode yang dapat dijalankan</strong> dan <strong>rich text</strong> dalam satu dokumen, beserta <strong>gambar</strong>, <strong>HTML</strong>, <strong>LaTeX</strong>, dan lainnya. Saat Anda membuat notebook Colab Anda sendiri, notebook tersebut akan disimpan di akun Google Drive Anda. Anda dapat dengan mudah membagikan notebook Colab Anda dengan rekan kerja atau teman, sehingga memungkinkan mereka memberikan komentar di notebook Anda atau bahkan mengeditnya. Untuk mempelajari lebih lanjut, buka <a href="/notebooks/basic_features_overview.ipynb">Ringkasan Colab</a>. Untuk membuat notebook Colab baru, Anda dapat menggunakan menu File di atas, atau menggunakan link berikut: <a href="http://colab.research.google.com#create=true">buat notebook Colab baru</a>.

Notebook Colab adalah notebook Jupyter yang dihosting oleh Colab. Untuk mempelajari project Jupyter lebih lanjut, buka <a href="https://www.jupyter.org">jupyter.org</a>.

<div class="markdown-google-sans">

## Ilmu data
</div>

Dengan Colab, Anda dapat memanfaatkan kecanggihan library Python yang populer untuk menganalisis dan memvisualisasikan data. Sel kode di bawah menggunakan <strong>numpy</strong> untuk menghasilkan beberapa data acak, dan menggunakan <strong>matplotlib</strong> untuk memvisualisasikannya. Untuk mengedit kode, cukup klik sel dan mulai pengeditan.
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""Anda dapat mengimpor data sendiri ke notebook Colab dari akun Google Drive Anda, termasuk dari spreadsheet, GitHub, dan berbagai sumber lainnya. Untuk mempelajari lebih lanjut pengimporan data dan bagaimana Colab dapat digunakan untuk ilmu data, lihat link di bawah pada bagian <a href="#working-with-data">Bekerja dengan Data</a>.

<div class="markdown-google-sans">

## Machine learning
</div>

Dengan Colab Anda dapat mengimpor set data gambar, melatih pengklasifikasi gambar pada gambar tersebut, dan mengevaluasi model, semuanya hanya dengan <a href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb">beberapa baris kode</a>. Notebook Colab mengeksekusi kode pada server cloud Google. Itu artinya Anda dapat memanfaatkan kecanggihan hardware Google, termasuk <a href="#using-accelerated-hardware">GPU dan TPU</a>, terlepas dari mesin yang Anda gunakan. Yang Anda butuhkan hanyalah browser.

Colab digunakan secara luas di komunitas machine learning dengan berbagai penerapan meliputi:
- Memulai TensorFlow
- Mengembangkan dan melatih jaringan neural
- Bereksperimen dengan TPU
- Menyebarkan riset AI
- Membuat tutorial

Untuk melihat sampel notebook Colab yang menunjukkan penerapan machine learning, lihat <a href="#machine-learning-examples">contoh machine learning</a> di bawah.

<div class="markdown-google-sans">

## Referensi Lainnya

### Bekerja dengan Notebook di Colab

</div>

- [Ringkasan Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Panduan tentang Markdown](/notebooks/markdown_guide.ipynb)
- [Mengimpor library dan menginstal dependensi](/notebooks/snippets/importing_libraries.ipynb)
- [Menyimpan dan memuat notebook di GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [Formulir interaktif](/notebooks/forms.ipynb)
- [Widget interaktif](/notebooks/widgets.ipynb)

<div class="markdown-google-sans">

<a name="working-with-data"></a>
### Bekerja dengan Data
</div>

- [Memuat data: Drive, Spreadsheet, dan Google Cloud Storage](/notebooks/io.ipynb)
- [Diagram: memvisualisasikan data](/notebooks/charts.ipynb)
- [Memulai BigQuery](/notebooks/bigquery.ipynb)

<div class="markdown-google-sans">

### Kursus Singkat Machine Learning

<div>

Berikut adalah beberapa notebook dari kursus Machine Learning online Google. Untuk info selengkapnya, buka <a href="https://developers.google.com/machine-learning/crash-course/">situs kursus lengkap</a>.
- [Pengantar Pandas DataFrame](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [Regresi linear dengan tf.keras menggunakan data sintetis](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb)

<div class="markdown-google-sans">

<a name="using-accelerated-hardware"></a>
### Menggunakan Hardware yang Diakselerasi
</div>

- [TensorFlow dengan GPU](/notebooks/gpu.ipynb)
- [TensorFlow dengan TPU](/notebooks/tpu.ipynb)

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### Contoh bagus

</div>

- <a href="https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/VoiceSwapSample.ipynb">NeMo Voice Swap</a>: Gunakan Toolkit AI percakapan NeMo Nvidia untuk menukar suara dalam fragmen audio dengan suara yang dihasilkan komputer.

- <a href="https://tensorflow.org/hub/tutorials/tf2_image_retraining">Melatih Kembali Pengklasifikasi Gambar</a>: Membangun model Keras di atas pengklasifikasi gambar yang telah terlatih untuk membedakan berbagai bunga.
- <a href="https://tensorflow.org/hub/tutorials/tf2_text_classification">Klasifikasi Teks</a>: Mengklasifikasikan ulasan film IMDB, baik sebagai <em>positif</em> ataupun <em>negatif</em>.
- <a href="https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization">Transfer Gaya</a>: Menggunakan deep learning untuk mentransfer gaya antar-gambar.
- <a href="https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa">Tanya Jawab Encoder Kalimat Universal Multibahasa</a>: Menggunakan model machine learning untuk menjawab pertanyaan dari set data SQuAD.
- <a href="https://tensorflow.org/hub/tutorials/tweening_conv3d">Jenis Interpolasi Video</a>: Memprediksi apa yang terjadi dalam suatu video antara bingkai pertama dan terakhir.
"""